from django.urls import path

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import (me_view, login_view, save_expo_push_token, register_user, chat_users_list,
                    coach_players_attendance_view, coach_matches_view, player_attendance_detail,
                    get_categories, player_trainings_view, add_reaction, delete_training_view, training_attendance_view,
                    set_training_attendance, list_clubs, test_push, create_training_view, user_categories_view,
                    training_detail_view, coach_trainings_view, change_password_view, chat_messages_view,
                    users_in_club, assign_role, remove_role, categories_in_club, coach_players_view,
                    training_update_view, club_detail, coach_attendance_summary, update_match_view,
                    all_players_with_roles, player_trainings_history_view, positions_list, player_matches_view,
                    create_match_participation, create_match_view, jersey_numbers_view, club_documents_view,
                    upload_document, match_delete_view, assign_players_to_category, match_stats_view, match_detail_view,
                    match_nominations_view, player_nominated_matches_view, admin_member_payments,
                    match_participation_view, club_payment_settings_detail,club_orders_view, orders_bulk_update,
                    upload_pdf_statement_chatgpt,OrderCreateView, MyOrdersListView, order_update_view,
                    set_preferred_role, club_payment_settings_list, member_payments, create_member_payments, payment_qr,
                    update_member_payment, remind_attendance_view, remind_match_attendance_view, orders_payments,generate_payment,
                    admin_member_payments_summary, new_members_without_payments,cancel_order_item_view, order_delete_view, create_jersey_order,
                    check_number)

urlpatterns = [
    path('me/', me_view, name='me'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('login/', login_view, name="login"),
    path('categories/<int:club_id>/', get_categories, name='get_categories'),
    path('player-trainings/', player_trainings_view, name='player_trainings'),
    path('set-training-attendance/', set_training_attendance, name='set_training_attendance'),
    path("trainings/", create_training_view, name="create-training"),
    path("user-categories/", user_categories_view),
    path('training-detail/<int:training_id>/', training_detail_view, name='training-detail'),
    path("save-token/", save_expo_push_token),
    path('test-push/', test_push),
    path("training/<int:training_id>/", delete_training_view),
    path("training-attendance/<int:training_id>/", training_attendance_view),
    path('coach-players-attendance/', coach_players_attendance_view),
    path('coach-trainings/', coach_trainings_view),
    path('change-password/', change_password_view),
    path('register/', register_user),
    path('clubs/', list_clubs),
    path('chat/<int:user_id>/', chat_messages_view, name='chat-messages'),
    path("chat-users/", chat_users_list),
    path("chat/<int:message_id>/react/", add_reaction, name="add-reaction"),
    path('users-in-club/', users_in_club),
    path('assign-role/', assign_role),
    path('remove-role/', remove_role),
    path('categories-in-club/', categories_in_club),
    path('categories-in-club/', coach_players_view),
    path('categories-in-club/', all_players_with_roles),
    path('categories-in-clubaaa/', all_players_with_roles),
    path("trainings/history/", player_trainings_history_view, name="player-trainings-all"),
    path("positions/", positions_list),
    path('matches/', player_matches_view, name='player_matches'),
    path('matches-coach/', coach_matches_view, name='coach_matches'),
    path('match-participations/', create_match_participation, name='create_match_participation'),
    path("matches/create/", create_match_view),
    path("jersey-numbers/", jersey_numbers_view),
    path("documents/", club_documents_view),
    path('upload-document/', upload_document, name='upload-document'),
    path("match-detail/<int:match_id>/", match_detail_view),
    path("match-nominations/<int:match_id>/", match_nominations_view),
    path('player-nominated-matches/', player_nominated_matches_view, name='player-nominated-matches'),
    path("match-participation/", match_participation_view),
    path("match-stats/<int:match_id>/", match_stats_view, name="match-stats"),
    path('matches/delete/<int:match_id>/', match_delete_view, name='match-delete'),
    path("trainings/<int:training_id>/", training_update_view, name="training-update"),
    path("assign-players-to-category/", assign_players_to_category, name="assign_players_to_category"),
    path("set-preferrd-role/", set_preferred_role, name="set_preferred_role"),
    path('clubs/<int:club_id>/', club_detail, name='club_detail'),
    path('coach-attendance-summary/', coach_attendance_summary, name='coach_attendance_summary'),
    path('player-attendance/<int:player_id>/', player_attendance_detail),
    path('club-payments-settings/', club_payment_settings_list),
    path('club-payments-settings/<int:pk>/', club_payment_settings_detail),
    path('member-payments/', member_payments),
    path('create-member-payments/', create_member_payments),
    path('member-payments/<int:pk>/', update_member_payment),
    path('admin-member-payments/', admin_member_payments),
    path("upload-pdf-chatgpt/", upload_pdf_statement_chatgpt),
    path("matches_edit/<int:match_id>/", update_match_view),
    path("remind-attendance/", remind_attendance_view),
    path("remind-match-attendance/", remind_match_attendance_view),
    path("admin-member-payments-summary/", admin_member_payments_summary),
    path('new-members-without-payments/', new_members_without_payments, name='new_members_without_payments'),
    path("orders/", OrderCreateView.as_view(), name="order-create"),
    path("my-orders/", MyOrdersListView.as_view(), name="my-orders"),
    path("club-orders/<int:club_id>/", club_orders_view, name="club-orders"),
    path("order/<int:order_id>/", order_update_view, name="order-update"),
    path("order-items/<int:item_id>/cancel/", cancel_order_item_view, name="cancel-order"),
    path('orders-payments/', orders_payments),
    path("payment-qr/<str:payment_type>/<int:pk>/", payment_qr, name="payment_qr"),
    path("order/<int:order_id>/generate-payment/", generate_payment),
    path("orders/bulk-update/", orders_bulk_update, name="orders-bulk-update"),
    path("order/<int:order_id>/delete/", order_delete_view, name="order-delete"),
    path("clubs/<int:club_id>/check-number/<int:number>/", check_number, name="check_number"),
    path("orders/jersey/", create_jersey_order, name="create_jersey_order"),






]


